// Shown when the server demands an access token (it is bound to something other than localhost).
// The token is generated by the server on first start and printed in its console.
import { useEffect, useState } from 'react'
import { KeyRound, ShieldAlert } from 'lucide-react'
import { getToken, setToken, useSync } from '../lib/sync'

export function TokenGate() {
  const authRequired = useSync((s) => s.authRequired)
  const [value, setValue] = useState('')
  const [error, setError] = useState('')

  useEffect(() => {
    if (authRequired) setValue(getToken())
  }, [authRequired])

  if (!authRequired) return null
  return (
    <div className="modal-backdrop" style={{ zIndex: 80 }}>
      <div className="modal" style={{ maxWidth: 440 }} role="dialog" aria-modal>
        <div className="flex" style={{ gap: 10, marginBottom: 12 }}>
          <ShieldAlert size={22} color="var(--orange)" />
          <h2>This server needs an access token</h2>
        </div>
        <p className="muted" style={{ fontSize: 13, lineHeight: 1.6 }}>
          The database server is not bound to localhost, so the API is protected. Paste the token printed in the server console (it is also stored in{' '}
          <span className="mono">data/.token</span>).
        </p>
        <form
          className="stack"
          style={{ gap: 12, marginTop: 14 }}
          onSubmit={async (e) => {
            e.preventDefault()
            setError('')
            setToken(value.trim())
            try {
              const r = await fetch('/api/health', { headers: { authorization: `Bearer ${value.trim()}` }, cache: 'no-store' })
              if (!r.ok) throw new Error(`HTTP ${r.status}`)
              window.location.reload()
            } catch {
              setError('That token was rejected — check the server console.')
            }
          }}
        >
          <input className="input" value={value} onChange={(e) => setValue(e.target.value)} placeholder="Paste token…" autoFocus />
          {error && <div style={{ color: 'var(--red)', fontSize: 13 }}>{error}</div>}
          <div className="modal-actions">
            <button className="btn primary" type="submit">
              <KeyRound size={14} /> Unlock
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
